#cloud-config
# Создать passwd hash: openssl passwd -6

timezone: Europe/Moscow

users:
  - name: ubuntu
    groups: [sudo]
    shell: /bin/bash
    lock_passwd: false
    passwd: "$6$u42qhP7hsnV3aM.w$HikwZmBp/zavB7JGzrer6TDG830JXI5g2jV4a6uyW0.WDAf.jrCLZ8nGAx7UuTwNiCeNopIY1mbr2Vjl3A7u00"
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - ${ssh_key}

package_update: true

packages:
  - qemu-guest-agent

runcmd:
  - systemctl enable --now qemu-guest-agent
  - hostnamectl set-hostname ${hostname}
  - systemctl disable --now packagekit
  - systemctl disable --now ModemManager
  - systemctl disable --now multipathd  

write_files:
  - path: /etc/hosts
    content: |
      127.0.0.1 localhost
      ${ipv4} ${hostname}

      # The following lines are desirable for IPv6 capable hosts
      ::1 ip6-localhost ip6-loopback
      fe00::0 ip6-localnet
      ff00::0 ip6-mcastprefix
      ff02::1 ip6-allnodes
      ff02::2 ip6-allrouters
      ff02::3 ip6-allhosts


final_message: "cloud-init finished"