#cloud-config
timezone: Europe/Moscow

users:
  - name: user
    groups: [wheel]
    shell: /bin/bash
    lock_passwd: false
    passwd: "$6$bqp3nBwI4R3D30rg$Gyx0u62YOyV2fYQsAzfD5n8Uk1MjABmsXslS8.gq6Q2/ge82Dpm.icNX6cVTiA53GJ6fw57rwMKuKGGfytWVb/"
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - ${ssh_key}


packages:
  - qemu-guest-agent

runcmd:
  - systemctl enable --now qemu-guest-agent
  - hostnamectl set-hostname ${hostname}